sdkversion: 4.0.0
name: rhodes-app
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.rhodes-app
  BundleURLScheme: rhodes-app
wp:
  productid: 689a2850-8ff7-0130-db8c-38f6b118e4ff
symbian:
  uid: '0xe8a1ed84'
android:
  version: '2.1'
extensions:
  - json
  - rhoconnect-client
  - rho-javascript
